[tool.poetry]
name = "example-consumer-python"
description = "Test to replicate a Docker Error"
authors = ["PactFlow"]
version = "0.1"

[tool.poetry.dependencies]
python = "^3.11"
Flask = "1.1.1"

[tool.poetry.group.dev.dependencies]
requests = "2.31.0"
pytest = "^7.2.1"
pact-python = "*"